functionsDirectory = "/opt/build/repo/netlify/functions"
functionsDirectoryOrigin = "config"
headersOrigin = "inline"
plugins = []
redirects = []

[build]
publish = "/opt/build/repo/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/opt/build/repo/netlify/functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[images]
remote_images = []

[functions]

  [functions."*"]

[[headers]]
for = "/_astro/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"